if(ANDROID)
    file(TO_CMAKE_PATH "${ANDROID_CONTRIB}/fmod" FMOD_ROOT)
    link_directories("${FMOD_ROOT}/lib")
elseif(EMSCRIPTEN)
    file(TO_CMAKE_PATH "$ENV{FMOD_HTML5_ROOT}" FMOD_ROOT)
    link_directories("${FMOD_ROOT}/lib/w32")
elseif(UNIX)
    file(TO_CMAKE_PATH "$ENV{FMOD_LINUX_ROOT}" FMOD_ROOT)
    link_directories("${FMOD_ROOT}/lib/x86_64")
else()
    file(TO_CMAKE_PATH "C:/Program Files (x86)/FMOD SoundSystem/FMOD Studio API Windows/api/core" FMOD_ROOT)
    link_directories("${FMOD_ROOT}/lib/x64")
endif()

include_directories("${FMOD_ROOT}/inc")